Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,18 +1,14 @@
 #!/usr/bin/env bash
-#Script that transfers a file from our client to a server
+# Write a Bash script that transfers 
+# a file from our client to a server
 
-# Check if all parameters are provided
-if [ $# -lt 4 ]; then
+if [ "$#" -ne 4 ]; then
   echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
+else
+  if [ ! -f "$1" ]; then
+    echo "'$1' file not found."
+    exit 1
+  fi
+
+  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
 fi
-
-file_path=$1
-server_ip=$2
-username=$3
-ssh_key=$4
-
-# Transfer the file using scp
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
-
-exit 0
